/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mzmine.mslibrary.lipid.validator;

import io.github.mzmine.util.spectraldb.parser.UnsupportedFormatException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        try {
            new MsLibraryReader().read(new File("/home/nilshoffmann/Projects/github.com/nilshoffmann/biohack23_p15/lipid_validation/mslibrary-lipid-validator/app/src/main/resources/PNNL-LIPIDS-NEGATIVE-small.mgf"));
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedFormatException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
